"""Render the report's results tables straight from artifacts/results/*.json.

Hand-typed numbers drift from the artifacts they claim to describe. REPORT.md
includes the file this writes, so the tables cannot silently disagree with the
run that produced them.
"""
import json, pathlib, sys

RES = pathlib.Path("artifacts/results")
ORDER = ["B0_majority", "B1_keyword", "B2_retrieval", "AGENT"]
LABEL = {"B0_majority": "B0 majority (trivial)", "B1_keyword": "B1 keyword (simple)",
         "B2_retrieval": "B2 retrieval-copy", "AGENT": "**AGENT**"}


def main() -> None:
    m = json.loads((RES / "metrics.json").read_text())
    out = [f"<!-- generated by scripts/make_tables.py; do not edit by hand -->",
           f"", f"Gold labels: `{m['gold_source']}` · {m['n_cases']} cases", ""]

    for sl, title in (("random", "Random slice (reflects real traffic mix)"),
                      ("enriched", "Enriched slice (rare/hard intents, NOT representative)")):
        out += [f"### {title}", "",
                "| system | n | intent acc | macro-F1 | routing acc | missed esc. | needless esc. | auto % | cost/case | reply quality |",
                "|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|"]
        for s in ORDER:
            e = m["systems"].get(s, {}).get(sl)
            if not e:
                continue
            r, q = e["routing"], e["reply_quality_auto_only"]
            qs = f"{q['mean_composite']:.2f}" if q.get("n_judged") else "—"
            out.append(
                f"| {LABEL[s]} | {e['n']} | {e['intent_accuracy']:.3f} | {e['intent_macro_f1']:.3f} | "
                f"{r['accuracy']:.3f} | {r['missed_escalation']} ({r['missed_escalation_rate']:.1%}) | "
                f"{r['needless_escalation']} ({r['needless_escalation_rate']:.1%}) | "
                f"{r['auto_rate']:.1%} | **{r['expected_cost']:.2f}** | {qs} |")
        out.append("")
    out += ["*cost/case* = expected cost under the declared 10:1 model "
            "(10 per missed escalation, 1 per needless). Lower is better.",
            "*reply quality* = judge composite (1–5) on cases that system actually auto-posts.", ""]

    # per-class table for the agent, on all items
    ag = m["systems"].get("AGENT", {}).get("all")
    if ag and "per_class" in ag:
        out += ["### AGENT per-intent (all items)", "",
                "| intent | precision | recall | F1 | support |", "|---|--:|--:|--:|--:|"]
        for k, v in sorted(ag["per_class"].items(), key=lambda kv: -kv[1]["support"]):
            if v["support"]:
                out.append(f"| `{k}` | {v['precision']:.2f} | {v['recall']:.2f} | "
                           f"{v['f1']:.2f} | {v['support']} |")
        out += ["", "Top confusions (gold → predicted):", ""]
        for (g, p), n in ag["top_confusions"]:
            out.append(f"- `{g}` → `{p}` ×{n}")
        out.append("")

    ap = RES / "agreement.json"
    if ap.exists():
        a = json.loads(ap.read_text())
        jh = a.get("judge_vs_human", {})
        out += ["### Judge vs human", ""]
        if jh.get("n"):
            out += [f"n = {jh['n']} blind human ratings.", "",
                    "| axis | exact | within 1 | human mean | judge mean | judge bias | Spearman ρ |",
                    "|---|--:|--:|--:|--:|--:|--:|"]
            for ax, v in jh["per_axis"].items():
                out.append(f"| {ax} | {v['exact']:.2f} | {v['within_1']:.2f} | {v['mean_human']:.2f} | "
                           f"{v['mean_judge']:.2f} | {v['judge_bias']:+.2f} | {v['spearman']:.2f} |")
            u = jh["unsupported_claim"]
            out += ["", f"Composite Spearman ρ = **{jh['composite_spearman']:.2f}**.", "",
                    f"`unsupported_claim` binary: agreement {u['agreement']:.2f}, "
                    f"Cohen's κ = **{u['cohens_kappa']:.2f}** "
                    f"(human flagged {u['human_flagged']}, judge flagged {u['judge_flagged']}, "
                    f"judge missed {u['judge_missed']}, false alarms {u['judge_false_alarm']}).", ""]
        else:
            out += [f"> **Not yet measured.** {jh.get('note','')}", ""]
        mp = a.get("machine_pass_agreement")
        if mp:
            out += [f"Two independent pre-annotation passes agreed on intent "
                    f"{mp['intent_agreement']:.1%} and on routing {mp['action_agreement']:.1%} "
                    f"(κ={mp['action_kappa']:.2f}, n={mp['n']}).", ""]
        gp = a.get("gold_provenance", {})
        if gp.get("n"):
            out += [f"Gold provenance: {gp['n']} items adjudicated by a human; "
                    f"{gp['human_changed']} ({gp['human_changed_rate']:.1%}) were changed "
                    f"from the machine proposal.", ""]
        else:
            out += [f"> **Gold provenance:** {gp.get('note','')}", ""]

    (RES / "tables.md").write_text("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
